micronaut:
  application:
    name: videogames
datasources:
  default:
    url: ${DB_URL:`jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE`}
    driverClassName: ${DB_DRIVER:org.h2.Driver}
    username: ${DB_USER:sa}
    password: ${DB_PASSWORD:}
    schema-generate: CREATE_DROP
    dialect: ${DB_DIALECT:H2}
jpa.default.properties.hibernate.hbm2ddl.auto: update

endpoint:
  all:
    sensitive: false
  health:
    enable: true
    sensitive: false
    details-visible: ANONYMOUS